### ISSUE TITLE
Arms Dealer doesn't show the "Change Shop" Menu

### ISSUE THREAD

**Issue by Desempregago** [Valks-Terraria-Mods/MerchantsPlus#9]
[What is happening](https://youtu.be/aTnvfIceS7Y)

**Comment by Steviegt6** [comment]
![image](https://user-images.githubusercontent.com/27323911/75213014-b173cf80-573d-11ea-81e3-ba48775fe1e3.png)
Seems to work fine for me.
Can you please verify that you're using the most up-to-date/recent version and there isn't any mod conflicts?
Thanks!

**Comment by Fogrits** [comment]
I've noticed that the problem happens after a certain progression stage, where a random NPC stops showing the cycle shop menu. I couldn't find any mods that could cause it to misbehave.

**Comment by valkyrienyanko** [comment]
This issue has gone away on its own after several commits I've pushed.
